import { StyleSheet } from 'react-native';

import {
  SPONSOR_TILE_GAP,
  SPONSOR_TILE_HEIGHT,
  SPONSOR_TILE_PADDING,
  SPONSOR_TILE_RADIUS,
  SPONSOR_TILE_WIDTH,
} from '@/constants/sponsorTiles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
    backgroundColor: '#FFFFFF',
  },
  contentContainerJoined: {
    paddingBottom: 158,
  },
  detailIntro: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
    backgroundColor: '#FFFFFF',
  },
  headerWrapper: {
    backgroundColor: '#FFFFFF',
    paddingBottom: 4,
  },
  headerToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  iconButton: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconButtonMeetup: {
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255,255,255,0.94)',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  rightHeaderActions: {
    flexDirection: 'row',
    gap: 10,
  },
  infoBlock: {
    marginBottom: 10,
  },
  /** Shared by `EventMetaChipsRow` (event detail + create preview card). */
  eventMetaChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  eventMetaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  eventMetaChipCategory: {
    backgroundColor: '#FFF7ED',
  },
  eventMetaChipDelivery: {
    backgroundColor: '#EEF2FF',
  },
  eventMetaChipFormat: {
    backgroundColor: '#ECFDF5',
  },
  /** When API has no stored format (should be rare after DB backfill). */
  eventMetaChipFormatPlaceholder: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  eventMetaChipCategoryText: {
    color: '#EA580C',
    fontWeight: '700',
    fontSize: 12,
  },
  eventMetaChipDeliveryText: {
    color: '#4338CA',
    fontWeight: '700',
    fontSize: 12,
  },
  eventMetaChipFormatText: {
    color: '#059669',
    fontWeight: '700',
    fontSize: 12,
  },
  eventMetaChipFormatTextPlaceholder: {
    color: '#6B7280',
    fontWeight: '600',
    fontSize: 12,
  },
  title: {
    fontSize: 23,
    lineHeight: 30,
    fontWeight: '600',
    color: '#111111',
  },
  /** Matches home feed event card title (`EventCard` feedTitle). */
  detailFeedTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
    color: '#1C1C1E',
  },
  descriptionWrap: {
    marginTop: 8,
  },
  description: {
    fontSize: 14,
    color: '#666666',
    lineHeight: 20,
  },
  readMore: {
    color: '#FF7A00',
    fontWeight: '600',
    fontSize: 14,
    marginTop: 10,
  },
  infoSpacing: {
    height: 16,
  },
  addToCalendarBtn: {
    marginTop: 10,
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FFF7ED',
    borderRadius: 12,
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#FFEDD5',
  },
  addToCalendarText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EA580C',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  infoIconBg: {
    padding: 10,
    backgroundColor: '#F2F3F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    marginRight: 12,
  },
  infoText: {
    fontSize: 14,
    color: '#111111',
    fontWeight: '600',
  },
  infoSubText: {
    fontSize: 13,
    color: '#666666',
    marginTop: 2,
  },
  mapContainer: {
    height: 114,
    borderRadius: 16,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
  },
  mapImage: {
    borderRadius: 16,
    resizeMode: 'cover',
    opacity: 0.22,
  },
  mapOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  mapButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  mapText: {
    marginLeft: 8,
    fontSize: 13,
    fontWeight: '600',
    color: '#FF7A00',
  },
  stickyMapButtonWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 84,
    alignItems: 'center',
    zIndex: 30,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111111',
    marginTop: 24,
    marginBottom: 12,
  },
  eventOrganizerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F0F0F0',
    backgroundColor: '#FAFAFA',
    gap: 12,
  },
  eventOrganizerRowDisabled: {
    opacity: 0.72,
  },
  eventOrganizerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  eventOrganizerAvatarFallback: {
    backgroundColor: '#FF8C42',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventOrganizerAvatarText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  eventOrganizerContent: {
    flex: 1,
    minWidth: 0,
  },
  eventOrganizerLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#9CA3AF',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  eventOrganizerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  eventOrganizerName: {
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '700',
    color: '#111111',
    lineHeight: 22,
  },
  eventOrganizerBadge: {
    marginLeft: 6,
    flexShrink: 0,
  },
  eventOrganizerChevron: {
    flexShrink: 0,
  },
  organizationCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 10,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  organizationLogo: {
    width: 50,
    height: 50,
    borderRadius: 14,
    marginRight: 12,
  },
  organizationLogoFallback: {
    backgroundColor: '#FF8C42',
    justifyContent: 'center',
    alignItems: 'center',
  },
  organizationLogoFallbackText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  organizationCardMain: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 0,
  },
  organizerFollowBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#FF7B3F',
    flexShrink: 0,
  },
  organizerFollowBtnActive: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FFB899',
  },
  organizerFollowBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  organizerFollowBtnTextActive: {
    color: '#FF7B3F',
  },
  organizationTextWrap: {
    flex: 1,
  },
  organizationNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  organizationName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111111',
  },
  organizationCategory: {
    fontSize: 13,
    color: '#666666',
    marginTop: 2,
  },
  speakersList: {
    gap: 12,
    paddingRight: 8,
  },
  speakerItem: {
    width: 110,
    alignItems: 'center',
  },
  speakerAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    marginBottom: 8,
  },
  speakerName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#111111',
    textAlign: 'center',
  },
  speakerRole: {
    marginTop: 3,
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  sponsorsRow: {
    flexDirection: 'row',
    marginBottom: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
  },
  sponsorCarouselList: {
    paddingVertical: 8,
    paddingBottom: 12,
  },
  /** Logo tile — detail carousel & create flow (no horizontal gap; add `sponsorCarouselSlot`). */
  sponsorLogoTile: {
    width: SPONSOR_TILE_WIDTH,
    height: SPONSOR_TILE_HEIGHT,
    borderRadius: SPONSOR_TILE_RADIUS,
    padding: SPONSOR_TILE_PADDING,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF0F4',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  sponsorCarouselSlot: {
    marginRight: SPONSOR_TILE_GAP,
  },
  sponsorDotsRow: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  sponsorDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
  },
  sponsorDotActive: {
    width: 16,
    backgroundColor: '#FF7A00',
  },
  sponsorsRowCentered: {
    justifyContent: 'center',
    flexGrow: 1,
    flexWrap: 'nowrap',
  },
  sponsorsRowGrid: {
    justifyContent: 'center',
  },
  sponsorLogoWrap: {
    width: '22%',
    minWidth: 88,
    maxWidth: 104,
    height: 76,
    borderRadius: 12,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    overflow: 'hidden',
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  sponsorLogoWrapCentered: {
    width: 104,
    minWidth: 104,
    maxWidth: 104,
  },
  sponsorLogo: {
    width: '100%',
    height: '100%',
    borderRadius: SPONSOR_TILE_RADIUS - 2,
  },
  sponsorLogoWrapGrid: {
    width: '22%',
    minWidth: 88,
    maxWidth: 104,
  },
  capacityBarInDetail: {
    marginTop: 4,
  },
  actionsSection: {
    marginTop: 6,
  },
  attendeesContainer: {
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  attendeeImages: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  attendeeAvatarOverlap: {
    marginLeft: -10,
  },
  attendeeImage: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
  },
  attendeeFallback: {
    backgroundColor: '#9CA3AF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attendeeAnonymous: {
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  attendeesText: {
    fontSize: 14,
    color: '#111111',
    fontWeight: '600',
  },
  attendeesArrow: {
    marginLeft: 'auto',
    opacity: 0.6,
  },
  bottomPriceColumn: {
    flexShrink: 1,
    minWidth: 0,
    marginRight: 12,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    paddingHorizontal: 20,
    paddingTop: 12,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 14,
  },
  bottomPriceLabel: {
    fontSize: 11,
    color: '#9CA3AF',
  },
  bottomPriceValue: {
    fontSize: 25,
    color: '#111111',
    fontWeight: '700',
    marginTop: 2,
  },
  bottomJoinButton: {
    alignSelf: 'flex-end',
    maxWidth: '100%',
    flexShrink: 1,
    borderRadius: 25,
    overflow: 'hidden',
    backgroundColor: '#FF7A00',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bottomJoinButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 50,
    paddingHorizontal: 22,
    paddingVertical: 14,
  },
  bottomJoinButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  bottomStatusBlock: {
    alignItems: 'flex-end',
    minWidth: 112,
  },
  bottomStatusValueRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bottomStatusValue: {
    fontSize: 20,
    fontWeight: '800',
    color: '#475569',
  },
  bottomJoinButtonDisabled: {
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  bottomJoinButtonClosed: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  bottomJoinButtonWaitlist: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  bottomJoinButtonTextDisabled: {
    color: '#6B7280',
  },
  bottomJoinButtonTextClosed: {
    color: '#B91C1C',
  },
  bottomJoinButtonTextWaitlist: {
    color: '#C2410C',
  },
  bottomActionWrap: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  bottomCtaSubtext: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  bottomJoinedActions: {
    flexDirection: 'row',
    gap: 10,
  },
  bottomGoingButton: {
    height: 44,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#FFD7BC',
    paddingHorizontal: 16,
    backgroundColor: '#FFF8F2',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bottomGoingButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FF7A00',
  },
  bottomAttendanceEditDivider: {
    width: 1,
    height: 16,
    backgroundColor: '#FFD7BC',
    marginHorizontal: 4,
  },
  bottomAttendanceEditLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FF7A00',
  },
  bottomShareButton: {
    height: 44,
    borderRadius: 16,
    paddingHorizontal: 20,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomShareButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  bottomGoingStatusCol: {
    flex: 1,
    minWidth: 0,
  },
  bottomYoureGoingLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0F172A',
  },
  bottomEditAttendanceLink: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: '700',
    color: '#FF7B3F',
  },
  bottomTicketButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FF7B3F',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
  },
  bottomTicketButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});